// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSfWkW6nl1mj2gAyF8G_cy2nZqZWNqDBY',
    appId: '1:273810036984:web:f97ff6c7b385791200430d',
    messagingSenderId: '273810036984',
    projectId: 'eeeew-7c2d8',
    authDomain: 'eeeew-7c2d8.firebaseapp.com',
    storageBucket: 'eeeew-7c2d8.appspot.com',
    measurementId: 'G-7LVD4LX20S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIxXoeXF7DfCriw2f0wg35eoVxPm6H3M0',
    appId: '1:273810036984:android:d3a5c12906b5152a00430d',
    messagingSenderId: '273810036984',
    projectId: 'eeeew-7c2d8',
    storageBucket: 'eeeew-7c2d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk7NeNZRb4IkMl65-320pqzkA3dMywJDg',
    appId: '1:273810036984:ios:d8f5cd781b7807ee00430d',
    messagingSenderId: '273810036984',
    projectId: 'eeeew-7c2d8',
    storageBucket: 'eeeew-7c2d8.appspot.com',
    iosClientId: '273810036984-14ta7n465r4qf5vrakk0u5l1qcina3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk7NeNZRb4IkMl65-320pqzkA3dMywJDg',
    appId: '1:273810036984:ios:d8f5cd781b7807ee00430d',
    messagingSenderId: '273810036984',
    projectId: 'eeeew-7c2d8',
    storageBucket: 'eeeew-7c2d8.appspot.com',
    iosClientId: '273810036984-14ta7n465r4qf5vrakk0u5l1qcina3ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
